org: jefalive
app: sls-guru-code-challenge-api
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  api:
    handler: dist/useCases/Todos/CreateTodo/handler
    events:
      - httpApi:
          path: /
          method: get
