org: jefalive
app: sls-guru-code-challenge-api
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:custom.stage}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb

package:
  individually: true

custom:
  stages:
    - local
    - dev
    - prod
  stage: ${opt:stage, 'dev'}
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  serverless-dynamodb:
    stages:
      - local
    start:
      port: 8000
      docker: true
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  save:
    handler: dist/useCases/Todos/CreateTodo/handler.handler
    events:
      - httpApi:
          path: /todos
          method: post

  find:
    handler: dist/useCases/Todos/FindTodo/handler.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: get

  list:
    handler: dist/useCases/Todos/ListTodo/handler.handler
    events:
      - httpApi:
          path: /todos
          method: get

  edit:
    handler: dist/useCases/Todos/EditTodo/handler.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: put

  delete:
    handler: dist/useCases/Todos/DeleteTodo/handler.handler
    events:
      - httpApi:
          path: /todos/{id}
          method: delete

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}