name: Deploy develop branch

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm dependencies
      run: npm ci
    - name: Build TypeScript
      run: npm run build
    - name: Run Unit Tests
      run: npm run test
    - name: Run DynamoDB Local
      uses: rrainn/dynamodb-action@v2.0.1
      with:
        dbPath: # undefined by default, if this is undefined inMemory will be used
        sharedDb: # undefined by default
        delayTransientStatuses: # undefined by default
        optimizeDbBeforeStartup: # undefined by default
        port: 8000
        cors: '*'
    - name: Run Migrations
      run: npm run db:migrate
    - name: Run Integration Tests
      run: npm run test:e2e
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy --stage dev
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}